// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: group.proto

package server

import (
	group2 "awesomeProject/proto/group"
	"context"

	"awesomeProject/app/group/rpc/internal/logic"
	"awesomeProject/app/group/rpc/internal/svc"
)

type GroupClientServer struct {
	svcCtx *svc.ServiceContext
	group2.UnimplementedGroupClientServer
}

func NewGroupClientServer(svcCtx *svc.ServiceContext) *GroupClientServer {
	return &GroupClientServer{
		svcCtx: svcCtx,
	}
}

func (s *GroupClientServer) AddFriend(ctx context.Context, in *group2.AddFriendRequest) (*group2.AddFriendResponse, error) {
	l := logic.NewAddFriendLogic(ctx, s.svcCtx)
	return l.AddFriend(in)
}

func (s *GroupClientServer) HandleFriend(ctx context.Context, in *group2.HandleFriendRequest) (*group2.HandleFriendResponse, error) {
	l := logic.NewHandleFriendLogic(ctx, s.svcCtx)
	return l.HandleFriend(in)
}

func (s *GroupClientServer) GroupUserList(ctx context.Context, in *group2.GroupUserListRequest) (*group2.GroupUserListResponse, error) {
	l := logic.NewGroupUserListLogic(ctx, s.svcCtx)
	return l.GroupUserList(in)
}

func (s *GroupClientServer) UserGroupList(ctx context.Context, in *group2.UserGroupListRequest) (*group2.UserGroupListResponse, error) {
	l := logic.NewUserGroupListLogic(ctx, s.svcCtx)
	return l.UserGroupList(in)
}

func (s *GroupClientServer) MessageGroupInfoList(ctx context.Context, in *group2.MessageGroupInfoListRequest) (*group2.MessageGroupInfoListResponse, error) {
	l := logic.NewMessageGroupInfoListLogic(ctx, s.svcCtx)
	return l.MessageGroupInfoList(in)
}
