// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package userclient

import (
	user2 "awesomeProject/proto/user"
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRequest         = user2.LoginRequest
	LoginResponse        = user2.LoginResponse
	PersonalInfoRequest  = user2.PersonalInfoRequest
	PersonalInfoResponse = user2.PersonalInfoResponse
	RegisterRequest      = user2.RegisterRequest
	RegisterResponse     = user2.RegisterResponse

	UserClient interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		PersonalInfo(ctx context.Context, in *PersonalInfoRequest, opts ...grpc.CallOption) (*PersonalInfoResponse, error)
	}

	defaultUserClient struct {
		cli zrpc.Client
	}
)

func NewUserClient(cli zrpc.Client) UserClient {
	return &defaultUserClient{
		cli: cli,
	}
}

func (m *defaultUserClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user2.NewUserClientClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user2.NewUserClientClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserClient) PersonalInfo(ctx context.Context, in *PersonalInfoRequest, opts ...grpc.CallOption) (*PersonalInfoResponse, error) {
	client := user2.NewUserClientClient(m.cli.Conn())
	return client.PersonalInfo(ctx, in, opts...)
}
