// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package server

import (
	user2 "awesomeProject/proto/user"
	"context"

	"awesomeProject/app/user/rpc/internal/logic"
	"awesomeProject/app/user/rpc/internal/svc"
)

type UserClientServer struct {
	svcCtx *svc.ServiceContext
	user2.UnimplementedUserClientServer
}

func NewUserClientServer(svcCtx *svc.ServiceContext) *UserClientServer {
	return &UserClientServer{
		svcCtx: svcCtx,
	}
}

func (s *UserClientServer) Login(ctx context.Context, in *user2.LoginRequest) (*user2.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserClientServer) Register(ctx context.Context, in *user2.RegisterRequest) (*user2.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserClientServer) PersonalInfo(ctx context.Context, in *user2.PersonalInfoRequest) (*user2.PersonalInfoResponse, error) {
	l := logic.NewPersonalInfoLogic(ctx, s.svcCtx)
	return l.PersonalInfo(in)
}
