// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: msg.proto

package server

import (
	msg2 "awesomeProject/proto/msg"
	"context"

	"awesomeProject/app/msg/rpc/internal/logic"
	"awesomeProject/app/msg/rpc/internal/svc"
)

type MessageClientServer struct {
	svcCtx *svc.ServiceContext
	msg2.UnimplementedMessageClientServer
}

func NewMessageClientServer(svcCtx *svc.ServiceContext) *MessageClientServer {
	return &MessageClientServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageClientServer) Upload(ctx context.Context, in *msg2.UploadRequest) (*msg2.UploadResponse, error) {
	l := logic.NewUploadLogic(ctx, s.svcCtx)
	return l.Upload(in)
}

func (s *MessageClientServer) Pull(ctx context.Context, in *msg2.PullRequest) (*msg2.PullResponse, error) {
	l := logic.NewPullLogic(ctx, s.svcCtx)
	return l.Pull(in)
}
