// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AddFriendRequest struct {
	UserId int64 `json:"user_id"`
}

type AddFriendResponse struct {
}

type ChatMsg struct {
	Id         int64  `json:"id"`
	GroupId    string `json:"groupId"`
	SenderId   int64  `json:"senderId"`
	Type       int64  `json:"type"`
	Content    string `json:"content"`
	Uuid       string `json:"uuid"`
	CreateTime int64  `json:"createTime"`
}

type GroupUserListRequest struct {
	GroupId string `json:"groupId"`
}

type GroupUserListResponse struct {
	List []int64 `json:"list"`
}

type HandleFriendRequest struct {
	GroupId string `json:"groupId"`
	IsAgree bool   `json:"isAgree"`
}

type HandleFriendResponse struct {
	GroupId string `json:"groupId"`
}

type MessageGroupInfo struct {
	GroupId   string   `json:"groupId"`
	AliasName string   `json:"aliasName"`
	AvatarUrl string   `json:"avatarUrl"`
	LastMsg   *ChatMsg `json:"lastMsg"`
}

type MessageGroupInfoListRequest struct {
}

type MessageGroupInfoListResponse struct {
	List []*MessageGroupInfo `json:"list"`
}
